### ISSUE TITLE
Kernel upgrade removes previous module

### ISSUE THREAD

**Issue by ajtucker** [datto/dattobd#156] opened 2018-08-31 09:27 UTC
Hi,

I'm using dattobd on Fedora 28, installed as per the instructions at https://github.com/datto/dattobd/blob/master/INSTALL.md#fedora

Each time the kernel gets updated, the dattobd module is successfully rebuilt and installed, but as part of the process, the current kernel's dattobd module is removed, which is causing issues with automated backups.

I'd like to stop the removal of the previous dattobd module, but after a quick look I couldn't tell whether this is a configuration issue in this project or whether I should look upstream to DKMS.

Cheers,
Alex.

**Comment by crawfxrd** [comment] 2018-08-31 13:01
This is caused by [dist/kernel.postinst.d/50-dattobd](https://github.com/datto/dattobd/blob/d1c8db9f91b7862efbd90fb95ad3f35275e202c0/dist/kernel.postinst.d/50-dattobd).

**Comment by crawfxrd** [comment] 2018-08-31 14:06
@Conan-Kudo do we need this logic? I don't see any incorrect behavior when I remove it from the package on CentOS 6, CentOS 7, or Fedora 28.

**Comment by Conan-Kudo** [comment] 2018-08-31 14:31
@crawfxrd We do it specifically for CentOS because we scan for a symbol during the build. Otherwise weak-modules carries the module over happily and breaks your boot next go around after you upgrade your kernel.

**Comment by crawfxrd** [comment] 2018-08-31 14:41
I tested kernel upgrades and it did not perform the weak install (module listed as `installed`, not `installed-weak`). I was able to reboot into the new kernel without a panic. It seems `NO_WEAK_MODULES` is honored now, but this will need investigation.

**Comment by Conan-Kudo** [comment] 2018-08-31 14:50
We can probably at least stop installing it on Fedora.

**Comment by crawfxrd** [comment] 2018-08-31 17:53
We need DKMS 2.3 for `NO_WEAK_MODULES`. CentOS 6 and 7 have a new enough versions now and do work testing them locally. I don't know about openSUSE 13.X, since they deleted the repositories when they went EOL.

openSUSE Leap 42.3 and 15 did not attempt to build the module on kernel upgrade _at all_ without `50-dattobd`. I'm not sure if it even attempted to run the default dkms postinst.

**Comment by crawfxrd** [comment] 2018-09-19 16:16
Fixed in 84ea26f and released in 0.10.7.

**Closed by crawfxrd** 2018-09-19 16:16 UTC
