### ISSUE TITLE
Poor performance in Centos 6 with Kernel 2.6.32-754.33.1

### ISSUE THREAD

**Issue by sub6as** [datto/dattobd#233] opened 2020-10-06 11:31 UTC
Hi,

When using Dattobd (0.10.13 or 0.10.9) with Centos 6 and 2.6.32-754.33.1 I'm seeing very slow read rates with DD, 6MB/s on average.

When using Kernel 4.4.237-1.el6.elrepo.x86_64 on the same server read rates with DD are 10x at 56MB/s

Are there any known good Kernel 2.6.32 versions that have been tested as I'd like to avoid using Kernel 4.4.237 if possible?

Regards
Arran

**Comment by yito24** [comment] 2020-10-23 08:18
I tried dd command.
But, I cannot reproduce.

Test result:
[root@Cent610 /]# dd if=/dev/datto0 of=/mnt_tmp/cent610_sda3-bk bs=1M
14183+0 records in
14183+0 records out
14871953408 bytes (15 GB) copied, 259.727 s, 57.3 MB/s
[root@Cent610 /]# uname -a
Linux Cent610 2.6.32-754.33.1.el6.x86_64 #1 SMP Tue Aug 25 18:30:34 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@Cent610 /]# cat /proc/datto-info 
{
	"version": "0.10.13",
	"devices": [
		{
			"minor": 0,
			"cow_file": "/.datto0",
			"block_device": "/dev/sda3",
			"max_cache": 314572800,
			"fallocate": 1486880768,
			"seq_id": 1,
			"uuid": "719475da033a4f6489968f222631ae4a",
			"version": 1,
			"nr_changed_blocks": 173685,
			"state": 3
		}
	]
}

**Comment by sub6as** [comment] 2020-10-28 11:45
Hi @yito24 Thanks for coming back to me, that's good news that you're seeing good performance with 2.6.32-754.33.1

Out of interest your testing device (/dev/sda3) is that in a virtual machine or physical device?

TIA

**Comment by yito24** [comment] 2020-10-31 13:36
My environment is a VM on ESXi 6.7.

**Comment by 105590023** [comment] 2022-01-21 07:38
Hi,
I have the same problem, when using Dattobd (0.10.11) in Centos 6.5 with kernel 2.6.32-431.el6.x86_64 read slowly with dd command.
My environment is also a VM on ESXi 6.7.

[root@CentOS65]# uname -a
Linux CentOS65 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
[root@CentOS65]# cat /proc/datto-info
{
        "version": "0.10.11",
        "devices": [
                {
                        "minor": 0,
                        "cow_file": "/snapshot0",
                        "block_device": "/dev/sdb1",
                        "max_cache": 314572800,
                        "fallocate": 21473787904,
                        "seq_id": 1,
                        "uuid": "4f4d6d79699444f9a861067f89026c25",
                        "version": 1,
                        "nr_changed_blocks": 806,
                        "state": 3
                }
        ]
}
[root@CentOS65]# dd if=/dev/datto0 of=/dev/null bs=8M count=1
1+0 records in
1+0 records out
8388608 bytes (8.4 MB) copied, 2.49551 s, 3.4 MB/s

I print debug log to watch bio info and found:
Every bio size is 1, it seems to divide sector in a small size. Maybe too many sector causing poor read performance.
[root@CentOS65]# dmesg
![image](https://user-images.githubusercontent.com/37138942/150482039-586d6fbc-b730-4f61-a8a2-044e6349a0f8.png)

It is the same test in CentOS 7.9:
[root@CentOS79]# dd if=/dev/datto0 of=/dev/null bs=8M count=1
1+0 records in
1+0 records out
8388608 bytes (8.4 MB) copied, 0.0395069 s, 212 MB/s
[root@CentOS79]# dmesg
![image](https://user-images.githubusercontent.com/37138942/150483565-124e9e92-c8c5-4ade-b30a-5ccce71ee638.png)

Is it possible fix the problem by changing bio size? Where can I found the bio size define?

Best Regards,
James

**Comment by 105590023** [comment] 2022-01-25 03:18
Hi,
After investigation, it is found that max_segment_size in CentOS6 environment is set to 4KB, and **_max_segment_size_** in CentOS7 is 64KB.
ps. The test environment is the same as my previous question

[root@CentOS6.5]# cat /sys/block/datto1/queue/max_segment_size
4096

[root@CentOS7.9]# cat /sys/block/datto1/queue/max_segment_size
65536

The reason is that the **_blk_alloc_queue_** function in **_dattobd.c_** causes.
I tried to replace it with blk_init_queue and the max_segment_size was successfully set to 64KB, but there are still other problems.
![image](https://user-images.githubusercontent.com/37138942/150904291-f05a9943-91b8-42ae-8f54-27e33944bfd1.png)

Can this problem be fixed in **_blk_alloc_queue_**? Or is there any other suggestion to solve this problem?

Best Regards,
James

**Comment by alphandbelt** [comment] 2024-04-08 07:56
> Hi, After investigation, it is found that max_segment_size in CentOS6 environment is set to 4KB, and **_max_segment_size_** in CentOS7 is 64KB. ps. The test environment is the same as my previous question
> 
> [root@CentOS6.5]# cat /sys/block/datto1/queue/max_segment_size 4096
> 
> [root@CentOS7.9]# cat /sys/block/datto1/queue/max_segment_size 65536
> 
> The reason is that the **_blk_alloc_queue_** function in **_dattobd.c_** causes. I tried to replace it with blk_init_queue and the max_segment_size was successfully set to 64KB, but there are still other problems. ![image](https://user-images.githubusercontent.com/37138942/150904291-f05a9943-91b8-42ae-8f54-27e33944bfd1.png)
> 
> Can this problem be fixed in **_blk_alloc_queue_**? Or is there any other suggestion to solve this problem?
> 
> Best Regards, James

hello, i also meet this problem
kernel is 
2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
can you haven fixed this problem?

**Comment by Swistusmen** [comment] 2024-04-08 09:10
Hi, we are currently focused on newer kernel distributions, for reference please check out our website:
https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html. Because of that I need to close this ticket as Centos 6 is deprecated by us, maybe in the future we'll come back to this, but cannot promise

**Closed by Swistusmen** 2024-04-08 09:10 UTC
