### ISSUE TITLE
Incremental files not updated in update-img

### ISSUE THREAD

**Issue by gopalnaidu** [datto/dattobd#29] opened 2016-03-24 06:48 UTC
I performed the following steps in ubuntu 14.04 with kernel version 4.2.0-27-generic 64 bit which has single ext4 partition /dev/sda1 

1. dbdctl setup-snapshot /dev/sda1 /.datto 0
2. dd if=/dev/datto0 of=/backups/sda1-bkp bs=1M
3. created files on base file system (total 5018847 bytes)
4. dbdctl transition-to-incremental 0
5. created file on base file system (total 30 bytes)
6. dbdctl transition-to-snapshot /.datto1 0
7. ran update-img /dev/datto0 /.datto /backups/sda1-bkp showed 109 blocks changes (109*4096 = 446464 bytes)

After incremental backup i mounted  /backups/sda1-bkp  to /mnt, New files created in step 3 and 5 not visible. Checked hexedit and saw that block offsets reported by update-img are updated but looks like the actual data was not copied. 

Is it a problem with this specific kernel or something we are doing wrong.

**Comment by tcaputi** [comment] 2016-03-24 19:15
We've actually been investigating this for a few days internally. Our tests so far have been inconclusive.... It seems that filesystems (particularly ones with 1024 byte block sizes, as is the default for ext when the volume is smaller than 1GB) is not honoring filesystem freezes or even calls to sync. That said, the driver seems to not be handling the writes very well either. I will update this ticket when I have more information.

**Comment by gopalnaidu** [comment] 2016-03-25 14:14
Hi while you investigate this can you point me to a kernel version and disk size that you have this working on. We tried it on redhat (2.6.32 with 8gb ext4) and ubuntu-14.04(4.2.0 with 4gb ext4) and could not make it get changes. Is there an older version that I can download for it to work?

**Comment by tcaputi** [comment] 2016-03-25 14:20
The problem seems to be with block sizes smaller than 4k. By default this only happens for volumes smaller than 1GB. We ran the test you posted above on several OS's without issue as long as the block size was 4k. You can check the block size for a filesystem with `blockdev --getbsz <device>`

**Comment by gopalnaidu** [comment] 2016-03-25 14:30
For both redhat and ubuntu blocksize is 4096.

Redhat(2.6.32-431.el6.i686 )
---------------------------------------------------------------------
[root@localhost test]# blockdev --getbsz /dev/dm-0 
4096

Ubuntu(4.2.0-27-generic)
---------------------------------------------------------------------
root@test:/home/test# blockdev --getbsz /dev/sda1 
4096

**Comment by crawfxrd** [comment] 2016-03-25 16:02
Confirmed the issue using an 8 GB ext4 volume on CentOS 6. `img-merge` from 0.8.13 did copy the blocks, so this looks like as issue with the changes to `update-img` in 0.9.0.

**Comment by tcaputi** [comment] 2016-03-26 02:39
I apologize for any confusion. It seems the latest release of dattobd had 2 separate bugs; one with the driver itself which effected (as I said) volumes with small block sizes and another unrelated regression with update-img. I just pushed 2 commits to master that should fix each of these respectively. These will be run through all of our testing on Monday, so I would hold off on using them until we tag a release (I expect Monday or Tuesday). I will leave this issue open until that time.

**Comment by crawfxrd** [comment] 2016-03-29 15:46
Fixed in 0.9.5

**Closed by crawfxrd** 2016-03-29 15:46 UTC
