### ISSUE TITLE
Centos 7 with default xfs file system

### ISSUE THREAD

**Issue by IronWolve** [datto/dattobd#5] opened 2015-09-24 23:06 UTC
Thought I'd try dattobd on centos 7 server running xfs, doesnt work. kicks an error.

>driver returned an error performing specified action. check dmesg for more info: Invalid argument

Then via DMESG

[207102.424197] dattobd: module verification failed: signature and/or required key missing - tainting kernel
[207286.766656] datto: fallocate is not supported for this file system, falling back on writing zeros
[207286.805662] datto: file specified is not on block device specified: -22
[207286.805855] datto: error setting up cow manager: -22
[207288.386614] datto: error setting up tracer as active snapshot: -22
[207288.386664] datto: error during setup ioctl handler: -22
[207303.521472] datto: fallocate is not supported for this file system, falling back on writing zeros
[207303.559139] datto: file specified is not on block device specified: -22
[207303.559186] datto: error setting up cow manager: -22
[207304.997633] datto: error setting up tracer as active snapshot: -22
[207304.997686] datto: error during setup ioctl handler: -22

**Comment by tcaputi** [comment] 2015-09-25 00:53
what command were you trying to run? and what was the mountpoint you were attempting to snapshot?

**Comment by tcaputi** [comment] 2015-10-01 23:05
Seeing as we were unable to reproduce this issue (and have taken snapshots of xfs on Centos 7 many times before I am going to close this issue. From the looks of the logs given it seems that the cow file specified was not on the volume specified, causing the error.

**Closed by tcaputi** 2015-10-01 23:05 UTC

**Comment by yingzhoujie** [comment] 2019-10-14 13:17
[root@localhost dattobd]# uname -r
3.10.0-1062.el7.x86_64

**Comment by yingzhoujie** [comment] 2019-10-14 13:18
Same problem
[root@localhost dattobd]# uname -r
3.10.0-1062.el7.x86_64

[root@localhost dattobd]# blkid
/dev/mapper/centos-root: UUID="cd0d30bf-5bbd-46f3-b076-014811be5351" TYPE="xfs" 
/dev/sda2: UUID="Memd0u-cz7M-PUml-0um1-mAv0-gEy0-CmdE47" TYPE="LVM2_member" 
/dev/sda1: UUID="a324b828-a926-4c4a-a0ec-ccca7dfcbbe6" TYPE="xfs" 
/dev/mapper/centos-swap: UUID="4859267f-ff4a-4468-82a6-4f1f1a8f76e6" TYPE="swap" 

[root@localhost dattobd]# df -h
Filesystem               Size  Used Avail Use% Mounted on
devtmpfs                 470M     0  470M   0% /dev
tmpfs                    487M     0  487M   0% /dev/shm
tmpfs                    487M  8.5M  478M   2% /run
tmpfs                    487M     0  487M   0% /sys/fs/cgroup
/dev/mapper/centos-root   17G  4.6G   13G  27% /
/dev/sda1               1014M  154M  861M  16% /boot
tmpfs                     98M   60K   98M   1% /run/user/0
